#!/bin/bash

APPLICATION_NAME=pikapp-web

source /home/ubuntu/.bashrc

if [ -f '/srv/pikapp-web/.env' ]; then
  rm -rf /srv/pikapp-web/.env
fi

if [ -f '/srv/ecosystem.json' ]; then
  rm -rf /srv/ecosystem.json
fi

aws s3 cp s3://pikapp-deployments/config/web.env /srv/pikapp-web/.env --region us-east-1 # Copy web.env -> .env
aws s3 cp s3://pikapp-deployments/config/ecosystem.json /srv/ecosystem.json --region us-east-1

cd /srv/pikapp-web/

npm install

cd /srv/

aws s3 cp s3://pikapp-deployments/config/slack.env /srv/slack.env
SLACK_HOOK=$(grep SLACK_DEPLOYMENT_HOOK '/srv/slack.env' | awk '{ print $2 }')
curl --silent --output /dev/null -X POST -H 'Content-type: application/json' --data "{\"text\":\"*$APPLICATION_NAME* has finished deploying\"}" $SLACK_HOOK
rm '/srv/slack.env'

pm2 start /srv/ecosystem.json

